#ifndef GAME_CONSTANTS_HPP
#define GAME_CONSTANTS_HPP

#include <string>

const int SCREEN_WIDTH = 800;
const int SCREEN_HEIGHT = 600;
const int MAX_NUM_OBSTACLES = 20;
const int MAX_NUM_COLLECTIBLES = 20;
const int MAX_NUM_LEVELS = 20;
const int MAX_NUM_EXITS = 10;
const int MS_PER_FRAME = 16;
const int MAX_NUM_LEVEL_TRANSITION_FRAMES = 30;
const int MAX_NUM_VACCUUM_CORD_POINTS = 60;
const int MAX_NUM_ANIMATIONS = 10;
const int MAX_NUM_FRAMES_PER_ANIMATION = 10;

const int KITCHEN_LEVEL_INDEX = 0;
const int BOTTOM_KITCHEN_LEVEL_INDEX = 1;
const int LIVING_ROOM_LEVEL_INDEX = 2;
const int HALLWAY_LEVEL_INDEX = 3;
const int OUTSIDE_LEVEL_INDEX = 4;
const int OFFICE_LEVEL_INDEX = 5;
const int BEDROOM_LEVEL_INDEX = 6;
const int BEDROOM_MAZE_1_LEVEL_INDEX = 7;
const int BEDROOM_MAZE_2_LEVEL_INDEX = 8;
const int COMPUTER_LEVEL_INDEX = 9;
const int DOOR_LEVEL_INDEX = 10;

#endif